"""nexus-contracts — Shared retrieval contract for the Nexus RAG platform."""

from nexus_contracts.chunk import (
    Audience,
    ChunkMetadata,
)
from nexus_contracts.document import (
    AccessContext,
    Candidat,
    ChunkMeta,
    DocumentMeta,
    Epreuve,
    Modality,
    Niveau,
    Rights,
    RIGHTS_ALLOWED_CONTEXTS,
    SourceType,
    StatutEnseignement,
    StrictBaseModel,
    TypeDoc,
    Voie,
)
from nexus_contracts.retrieval import (
    Citation,
    RetrievalNeed,
    RetrievalOptions,
    RetrievalRequest,
    RetrievalResponse,
    RetrievalResult,
)
from nexus_contracts.chat import (
    ChatCitation,
    ChatMessage,
    ChatPayload,
    ChatRequest,
    ChatResponse,
    SearchPayload,
)
from nexus_contracts.student_profile import (
    StatusDetail,
    StudentProfile,
)
from nexus_contracts.identity import (
    InternalIdentity,
    InternalIdentityEnvelope,
    PedagogicalProfile,
)
from nexus_contracts.scope import (
    PILOT_RETRIEVAL_SCOPE_DIGEST,
    PilotRetrievalScopeArtifact,
    PilotScopeIdentity,
    PilotScopeSubject,
    load_pilot_retrieval_scope,
)
from nexus_contracts.review import (
    ReviewDecisionPayload,
    ReviewDecisionRequest,
    ReviewDecisionResponse,
    ReviewQueueDocument,
    ReviewQueuePayload,
    ReviewQueueResponse,
)
from nexus_contracts.ingestion import (
    ArtifactRecord,
    CollectionProfile,
    CoverageSnapshot,
    IngestionRun,
    PublicationPolicy,
    QualityReport,
    ResourceCandidate,
    ResourceScope,
    RoutingDecision,
    SearchPlan,
)
from nexus_contracts.resource_state import (
    ALLOWED_RESOURCE_TRANSITIONS,
    NORMAL_SEQUENCE,
    ResourceState,
    is_valid_resource_transition,
)
from nexus_contracts.scope_authorization import (
    AUTHORIZE_INGESTION_SCOPE_DECISION,
    GitHubApprovalEvidence,
    ScopeAuthorization,
    ScopeAuthorizationRevocation,
    is_expired,
)
from nexus_contracts.publication_attestation import (
    PROTOCOL_VERSION as LOT42_PROTOCOL_VERSION,
    GateAttestation,
    HumanReviewEvidence,
    PublicationAttestation,
    QualityAttestation,
    RightsAttestation,
    is_invalidated_by_content_change,
    is_invalidated_by_manifest_drift,
    is_invalidated_by_profile_drift,
)

__all__ = [
    "AccessContext",
    "Audience",
    "Candidat",
    "ChunkMeta",
    "ChunkMetadata",
    "Citation",
    "DocumentMeta",
    "Epreuve",
    "Modality",
    "Niveau",
    "RIGHTS_ALLOWED_CONTEXTS",
    "RetrievalNeed",
    "RetrievalOptions",
    "RetrievalRequest",
    "RetrievalResponse",
    "RetrievalResult",
    "ReviewDecisionPayload",
    "ReviewDecisionRequest",
    "ReviewDecisionResponse",
    "ReviewQueueDocument",
    "ReviewQueuePayload",
    "ReviewQueueResponse",
    "ChatCitation",
    "ChatMessage",
    "ChatPayload",
    "ChatRequest",
    "ChatResponse",
    "SearchPayload",
    "Rights",
    "SourceType",
    "StatusDetail",
    "StatutEnseignement",
    "StrictBaseModel",
    "StudentProfile",
    "InternalIdentity",
    "InternalIdentityEnvelope",
    "PedagogicalProfile",
    "PILOT_RETRIEVAL_SCOPE_DIGEST",
    "PilotRetrievalScopeArtifact",
    "PilotScopeIdentity",
    "PilotScopeSubject",
    "TypeDoc",
    "Voie",
    "load_pilot_retrieval_scope",
    "ArtifactRecord",
    "CollectionProfile",
    "CoverageSnapshot",
    "IngestionRun",
    "PublicationPolicy",
    "QualityReport",
    "ResourceCandidate",
    "ResourceScope",
    "RoutingDecision",
    "SearchPlan",
    "ALLOWED_RESOURCE_TRANSITIONS",
    "NORMAL_SEQUENCE",
    "ResourceState",
    "is_valid_resource_transition",
    "AUTHORIZE_INGESTION_SCOPE_DECISION",
    "GitHubApprovalEvidence",
    "ScopeAuthorization",
    "ScopeAuthorizationRevocation",
    "is_expired",
    "LOT42_PROTOCOL_VERSION",
    "GateAttestation",
    "HumanReviewEvidence",
    "PublicationAttestation",
    "QualityAttestation",
    "RightsAttestation",
    "is_invalidated_by_content_change",
    "is_invalidated_by_manifest_drift",
    "is_invalidated_by_profile_drift",
]
